site_name: JACoW - CAT - MEOW
theme: 
  name: material
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
repo_name: 'jacow-org/docs-MEOW'
repo_url: 'https://github.com/JACoW-org/docs-MEOW'
plugins:
  - privacy
  - search
  - open-in-new-tab:
      add_icon: true
nav:
  - Introduction: index.md
  - Framework: framework.md
  - API: api.md
  - Events:
    - Introduction: events/intro.md
    - Abstract Booklet: events/abstractBooklet.md
    - PDF check: events/pdfCheck.md
    - Proceedings: events/proceedings.md
    - Compress Proceedings: events/compress.md
    - DOI: events/doi.md
  - Tools:
    - Jinja: tools/jinja.md
    - Hugo: tools/hugo.md
    - Keywords Extraction: tools/keywords.md
  - Installation: install.md
